# 配置端口
server:
  port: 8080
  contextPath:
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  # 配置数据源
  data.mongodb:
    host: xx.xxx.xxx.xxx
    port: xxxx
    database: xxx
    username: xxx
    password: xxx

# 日志配置
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG