# 配置端口
server:
  port: 8080
  contextPath:
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  # 配置数据源
  data.mongodb:


# JWT配置
jwt:
  # 密匙KEY
  secret: JWTSecret
  # HeaderKEY
  tokenHeader: Authorization
  # Token前缀字符
  tokenPrefix: Sans-
  # 过期时间 单位秒 1天后过期=86400 7天后过期=604800
  expiration: 86400
  # 配置不需要认证的接口
  antMatchers: /index/**,/login/**,/favicon.ico

# 日志配置
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG